// Sources/ARTSdk/WebSocket/LiveObjSubscription.swift

import Foundation

public final class LiveObjSubscription: BaseSubscription {

    public let crdt: CRDT

    public override init(
        connectionID: String,
        channelConfig: ChannelConfig,
        websocketHandler: IWebsocketHandler,
        process: String = "subscribe"
    ) {

        let snapshotMap: LDMap
        if let snap = channelConfig.snapshot {
            snapshotMap = fromAnyToLDMap(snap)
        } else {
            snapshotMap = LDMap()
        }

        let crdtInstance = CRDT(initial: snapshotMap) { _ in }

        crdtInstance.setReplicaId("r-\(UUID().uuidString.prefix(8).lowercased())")

        self.crdt = crdtInstance

        super.init(
            connectionID: connectionID,
            channelConfig: channelConfig,
            websocketHandler: websocketHandler,
            process: process
        )

        crdt.setMergeCallback { [weak self] ops in
            self?.executeServerMerge(ops)
        }
    }

    // MARK: - Public API
    public func state() -> CRDTProxy {
        crdt.state()
    }

    public func flush() async {
        await crdt.flush()
    }

    public func query(path: String) -> CRDT.QueryHandle {
        crdt.query(path: path)
    }
    
    // MARK: - Send CRDT ops to server
    
    private func executeServerMerge(_ ops: [CRDTOperation]) {

        guard !ops.isEmpty else { return }
        guard websocketHandler.getConnection() != nil else { return }

        let serializedOps = serializeOps(ops)

        Task { [weak self] in
            do {
                try await self?.pushArray(event: "merge", data: serializedOps)
            } catch {
return            }
        }
    }

    public override func handleMessage(event: String, payload: [String: Any]) async {

        // Ignore self-ack packets
        let returnFlag = payload["return_flag"] as? String ?? ""
        if returnFlag == "SA" { return }

        // Presence events
        if event == "art_presence" {
            if let content = payload["data"] {
                emitter.emit("art_presence", content)
            }
            return
        }

        // ---- CRDT UPDATE / MERGE EVENTS ----
        let rawContent = payload["content"] ?? payload["data"]
        guard let content = rawContent else { return }

        var rawOps: [[String: Any]]?

        // Case 1: Already an array
        if let ops = content as? [[String: Any]] {
            rawOps = ops
        }

        // Case 2: JSON string
        else if let str = content as? String {

            if let json = str.data(using: .utf8),
               let parsed = try? JSONSerialization.jsonObject(with: json) {

                // Normal stringified array
                if let arr = parsed as? [[String: Any]] {
                    rawOps = arr
                }

                // Double-encoded JSON string
                else if let innerStr = parsed as? String,
                        let innerData = innerStr.data(using: .utf8),
                        let arr = try? JSONSerialization.jsonObject(with: innerData) as? [[String: Any]] {

                    rawOps = arr
                }
            }
        }

        guard let opsDict = rawOps else {
            return
        }

        // Convert dictionaries → CRDTOperation
        let ops = deserializeOps(opsDict)

        if ops.isEmpty { return }

        let myReplica = crdt.getReplicaId()

        // Ignore operations generated by this client
        let filtered = ops.filter { $0.replicaId != myReplica }

        if filtered.isEmpty { return }

        // Apply remote operations
        crdt.merge(filtered)
    }
    
}

// MARK: - Serialisation Op
private func serializeOps(_ sOps: [CRDTOperation]) -> [[String: Any]] {
    return sOps.map { op in
        switch op {
        case .add(let path, let entry, let ts, let replicaId):
            var d: [String: Any] = ["op": "add", "path": path, "timestamp": Int(ts), "replicaId": replicaId]
            if let e = entry { d["entry"] = serializeEntry(e) }
            return d
        case .replace(let path, let entry, let ts, let replicaId):
            return ["op": "replace", "path": path, "entry": serializeEntry(entry), "timestamp": Int(ts), "replicaId": replicaId]
        case .remove(let path, let ts, let replicaId):
            return ["op": "remove", "path": path, "timestamp": ts, "replicaId": replicaId]
        case .arrayPush(let path, let ref, let entry, let ts, let replicaId):
            var d: [String: Any] = ["op": "array-push", "path": path, "entry": serializeEntry(entry), "timestamp": Int(ts), "replicaId": replicaId]
            if let r = ref { d["ref"] = r }
            return d
        case .arrayUnshift(let path, let entry, let ts, let replicaId):
            return ["op": "array-unshift", "path": path, "entry": serializeEntry(entry), "timestamp": Int(ts), "replicaId": replicaId]
        case .arrayRemove(let path, let ref, let ts, let replicaId):
            return ["op": "array-remove", "path": path, "ref": ref, "timestamp": Int(ts), "replicaId": replicaId]
        }
    }
}

private func serializeEntry(_ entry: LDEntry) -> [String: Any] {
    let d: [String: Any] = [
        "id": entry.id, "key": entry.key, "type": entry.type.rawValue,
        "value": serializeValue(entry.value, replicaId: entry.meta.replicaId),
        "meta": serializeMeta(entry.meta)
    ]
    return d
}

private func serializeMeta(_ meta: LDMeta) -> [String: Any] {
    var d: [String: Any] = ["updatedAt": Int(meta.updatedAt), "version": meta.version, "replicaId": meta.replicaId]
    if let t = meta.tombstone { d["tombstone"] = t }
    if let a = meta.after {
        d["after"] = a as Any
    }
    return d
}

private func serializeValue(_ value: LDValue, replicaId: String) -> Any {

    switch value {
    case .string(let s):
        return s

    case .number(let n):
        return n

    case .boolean(let b):
        return b

    case .null:
        return NSNull()

    case .map(let m):

        var dict: [String: Any] = [:]

        for (key, entry) in m.index {

            if key == "index",
               case .map(let innerMap) = entry.value {

                var indexDict: [String: Any] = [:]

                for (k, v) in innerMap.index {
                    indexDict[k] = serializeEntry(v)
                }

                dict["index"] = indexDict

            } else {
                dict[key] = serializeEntry(entry)
            }
        }

        dict["meta"] = [
            "updatedAt": m.meta.updatedAt,
            "version": m.meta.version,
            "replicaId": replicaId
        ]

        return dict

    case .array(let a):

        var dict: [String: Any] = [:]

        for (id, entry) in a.entries {
            dict[id] = serializeEntry(entry)
        }

        return dict
    }
}

private func deserializeOps(_ dOps: [[String: Any]]) -> [CRDTOperation] {
    return dOps.compactMap { d -> CRDTOperation? in
        guard let op = d["op"] as? String,
              let path = d["path"] as? [String],
              let ts = d["timestamp"] as? Int,
              let replicaId = d["replicaId"] as? String else { return nil }

        switch op {
        case "add":
            let entry = (d["entry"] as? [String: Any]).map(deserializeEntry)
            return .add(path: path, entry: entry, timestamp: Int(ts), replicaId: replicaId)
        case "replace":
            guard let entryDict = d["entry"] as? [String: Any] else { return nil }
            return .replace(path: path, entry: deserializeEntry(entryDict), timestamp: Int(ts), replicaId: replicaId)
        case "remove":
            return .remove(path: path, timestamp: Int(ts), replicaId: replicaId)
        case "array-push":
            guard let entryDict = d["entry"] as? [String: Any] else { return nil }
            return .arrayPush(path: path, ref: d["ref"] as? String, entry: deserializeEntry(entryDict), timestamp: Int(ts), replicaId: replicaId)
        case "array-unshift":
            guard let entryDict = d["entry"] as? [String: Any] else { return nil }
            return .arrayUnshift(path: path, entry: deserializeEntry(entryDict), timestamp: Int(ts), replicaId: replicaId)
        case "array-remove":
            guard let ref = d["ref"] as? String else { return nil }
            return .arrayRemove(path: path, ref: ref, timestamp: Int(ts), replicaId: replicaId)
        default:
            return nil
        }
    }
}

private func deserializeEntry(_ dEntry: [String: Any]) -> LDEntry {

    let id    = dEntry["id"] as? String ?? generateId()
    let key   = dEntry["key"] as? String ?? id
    let type_ = LDEntry.LDEntryType(rawValue: dEntry["type"] as? String ?? "object") ?? .object

    // ---- VALUE ----
    let value: LDValue

    if let val = dEntry["value"] {

        if type_ == .object, let dict = val as? [String: Any] {

            let ldMap = LDMap()

            for (k, v) in dict {

                if let entryDict = v as? [String: Any],
                   entryDict["id"] != nil {

                    // Nested LDEntry
                    ldMap.index[k] = deserializeEntry(entryDict)

                } else {

                    // Primitive value
                    let ldVal = toLDValue(v)

                    ldMap.index[k] = LDEntry(
                        id: generateId(),
                        key: k,
                        type: determineType(ldVal),
                        value: ldVal,
                        meta: LDMeta(
                            updatedAt: Int(nowMs()),
                            version: 1,
                            replicaId: "remote"
                        )
                    )
                }
            }

            value = .map(ldMap)

        } else {
            value = toLDValue(val)
        }

    } else {
        value = .null
    }

    // ---- META ----
    var meta = LDMeta()

    if let m = dEntry["meta"] as? [String: Any] {

        meta.updatedAt = m["updatedAt"] as? Int ?? Int(nowMs())
        meta.version   = m["version"] as? Int ?? 1
        meta.replicaId = m["replicaId"] as? String ?? "remote"
        meta.tombstone = m["tombstone"] as? Bool

        if m.keys.contains("after") {
            meta.after = .some(m["after"] as? String)
        }
    }

    return LDEntry(
        id: id,
        key: key,
        type: type_,
        value: value,
        meta: meta
    )
}




