// Sources/ArtAdk/Agentic/Run.swift
//
// Handle for a single logical conversation with an agent.

import Foundation

/// Lifecycle errors surfaced by a `Run` that are NOT agent-emitted
/// `AgentError`s. Callers typically swallow these (a supersede is normal
/// when a follow-up run starts on the same thread).
public enum RunLifecycleError: Error {
    /// The run was force-closed because a newer run started on the same
    /// thread.
    case superseded(String)
    /// The run was closed before any terminal event arrived.
    case closed(String)
}

/// Handle for a single logical conversation with the agent.
///
/// `done()` resolves with the agent's `AgentOutput` on the terminal
/// `agent_general_response`, or throws the typed `AgentError` on
/// `agent_error_response`. `sendFeedback(_:)` answers the most recent
/// `HumanInputRequest` for this run by sending a `user_reply` carrying the
/// matching `reply_id`. Multi-turn HITL stays inside one `Run` until the
/// agent emits a terminal event.
public final class Run {

    private let thread: AgentThread
    private let lock: ArtLock = ArtLock()

    private var _refId: String = ""
    private var continuation: CheckedContinuation<AgentOutput, Error>?
    private var settledResult: Result<AgentOutput, Error>?
    private var latestHumanInputRef: String?
    private var humanInputTimer: Task<Void, Never>?
    private var closed = false

    init(_ thread: AgentThread) {
        self.thread = thread
    }

    /// Outbound `ref_id` generated by the SDK when the originating
    /// `user_input` was pushed. Empty until the push completes.
    public var refId: String { lock.sync { _refId } }

    /// Whether the run has terminated.
    public var isClosed: Bool { lock.sync { closed } }

    /// Resolves on the agent's terminal `agent_general_response`. Throws
    /// the typed `AgentError` on `agent_error_response`, or a
    /// `RunLifecycleError` when the run is force-closed without a terminal
    /// event.
    public func done() async throws -> AgentOutput {
        if let settled = lock.sync({ settledResult }) { return try settled.get() }
        return try await withCheckedThrowingContinuation { cont in
            let settled: Result<AgentOutput, Error>? = lock.sync {
                if let settledResult { return settledResult }
                continuation = cont
                return nil
            }
            if let settled { cont.resume(with: settled) }
        }
    }

    // MARK: - Internal

    func setRefId(_ value: String) { lock.sync { _refId = value } }

    /// Feeds an inbound event to this run. Invoked by `AgentThread`.
    func push(_ envelope: AgentEventEnvelope) {
        if isClosed { return }

        switch envelope.payload {
        case .humanInput(let content):
            // Prefer the inbound message's own ref_id; fall back to its
            // explicit reply_to when ref_id is missing.
            let pendingRef = !content.refId.isEmpty
                ? content.refId
                : (!content.replyTo.isEmpty ? content.replyTo : nil)
            lock.sync { latestHumanInputRef = pendingRef }
            clearHumanInputTimer()
            if let timeoutSec = content.timeout, timeoutSec > 0 {
                let captured = content
                let timer = Task { [weak self] in
                    try? await Task.sleep(
                        nanoseconds: UInt64(timeoutSec * 1_000_000_000)
                    )
                    guard let self, !Task.isCancelled else { return }
                    let replyTo: String? = self.lock.sync {
                        guard !self.closed else { return nil }
                        self.closed = true
                        return self.latestHumanInputRef ?? ""
                    }
                    guard let replyTo else { return }
                    let err = AgentError(
                        code: "HUMAN_INPUT_TIMEOUT",
                        message: "No response received within \(timeoutSec)s for human_input_request.",
                        details: ["prompt": captured.prompt, "timeout": timeoutSec],
                        threadId: captured.threadId,
                        refId: "",
                        agentId: captured.agentId,
                        replyTo: replyTo
                    )
                    self.settle(.failure(err))
                    self.thread.closeRun(self)
                }
                lock.sync { humanInputTimer = timer }
            }
            thread.fireRequestFeedback(content, self)

        case .output(let content):
            guard markClosed() else { return }
            settle(.success(content))
            thread.closeRun(self)

        case .error(let content):
            guard markClosed() else { return }
            settle(.failure(content))
            thread.closeRun(self)

        case .wait, .plannerCorrection, .threadState, .unknown:
            // Non-terminal — surfaced to listeners but does not settle.
            break
        }
    }

    /// Sends a reply to the most recent `HumanInputRequest`.
    ///
    /// Throws `RunLifecycleError.closed` when no input is currently
    /// pending. The reply is sent as `user_reply` with `reply_id` set to
    /// the originating request's `ref_id` so the server can route it back
    /// into the paused run.
    public func sendFeedback(_ value: Any) async throws {
        // Consume the pending input *before* sending so a reentrant
        // handler doesn't double-respond.
        let replyId: String? = lock.sync {
            let pending = latestHumanInputRef
            latestHumanInputRef = nil
            return pending
        }
        guard let replyId else {
            throw RunLifecycleError.closed(
                "Run.sendFeedback: no pending human_input_request to respond to."
            )
        }
        clearHumanInputTimer()
        _ = try await thread.sendReply(value, replyId)
    }

    /// Force-closes the run. Invoked by `AgentThread` on supersede.
    func close(_ reason: String = "Run closed before terminal event") {
        guard markClosed() else { return }
        settle(.failure(RunLifecycleError.superseded(reason)))
    }

    /// Marks the run closed and cancels the HITL timer. Returns `false`
    /// when it was already closed.
    private func markClosed() -> Bool {
        let timer: Task<Void, Never>?? = lock.sync {
            guard !closed else { return nil }
            closed = true
            let timer = humanInputTimer
            humanInputTimer = nil
            return .some(timer)
        }
        guard let timer else { return false }
        timer?.cancel()
        return true
    }

    private func settle(_ result: Result<AgentOutput, Error>) {
        let cont: CheckedContinuation<AgentOutput, Error>? = lock.sync {
            guard settledResult == nil else { return nil }
            settledResult = result
            let cont = continuation
            continuation = nil
            return cont
        }
        cont?.resume(with: result)
    }

    private func clearHumanInputTimer() {
        let timer: Task<Void, Never>? = lock.sync {
            let timer = humanInputTimer
            humanInputTimer = nil
            return timer
        }
        timer?.cancel()
    }
}
