// Sources/ArtAdk/Agentic/Run.swift
//
// Handle for a single logical conversation with an agent. Mirrors
// `js-adk-common/agentic/run.ts` and the Flutter `lib/src/agentic/run.dart`.

import Foundation

/// Lifecycle errors surfaced by a `Run` that are NOT agent-emitted
/// `AgentError`s. Callers typically swallow these (a supersede is normal
/// when a follow-up run starts on the same thread).
public enum RunLifecycleError: Error {
    /// The run was force-closed because a newer run started on the same
    /// thread.
    case superseded(String)
    /// The run was closed before any terminal event arrived.
    case closed(String)
}

/// Handle for a single logical conversation with the agent.
///
/// `done()` resolves with the agent's `AgentOutput` on the terminal
/// `agent_general_response`, or throws the typed `AgentError` on
/// `agent_error_response`. `sendFeedback(_:)` answers the most recent
/// `HumanInputRequest` for this run by sending a `user_reply` carrying the
/// matching `reply_id`. Multi-turn HITL stays inside one `Run` until the
/// agent emits a terminal event.
public final class Run {

    private let thread: AgentThread

    /// Outbound `ref_id` generated by the SDK when the originating
    /// `user_input` was pushed. Empty until the push completes.
    public private(set) var refId: String = ""

    private var continuation: CheckedContinuation<AgentOutput, Error>?
    private var settledResult: Result<AgentOutput, Error>?
    private var latestHumanInputRef: String?
    private var humanInputTimer: Task<Void, Never>?
    private var closed = false

    init(_ thread: AgentThread) {
        self.thread = thread
    }

    /// Whether the run has terminated.
    public var isClosed: Bool { closed }

    /// Resolves on the agent's terminal `agent_general_response`. Throws
    /// the typed `AgentError` on `agent_error_response`, or a
    /// `RunLifecycleError` when the run is force-closed without a terminal
    /// event.
    public func done() async throws -> AgentOutput {
        if let settledResult { return try settledResult.get() }
        return try await withCheckedThrowingContinuation { cont in
            if let settledResult {
                cont.resume(with: settledResult)
            } else {
                continuation = cont
            }
        }
    }

    // MARK: - Internal

    func setRefId(_ value: String) { refId = value }

    /// Feeds an inbound event to this run. Invoked by `AgentThread`.
    func push(_ envelope: AgentEventEnvelope) {
        if closed { return }

        switch envelope.payload {
        case .humanInput(let content):
            // Prefer the inbound message's own ref_id; fall back to its
            // explicit reply_to when ref_id is missing.
            latestHumanInputRef = !content.refId.isEmpty
                ? content.refId
                : (!content.replyTo.isEmpty ? content.replyTo : nil)
            clearHumanInputTimer()
            if let timeoutSec = content.timeout, timeoutSec > 0 {
                let captured = content
                humanInputTimer = Task { [weak self] in
                    try? await Task.sleep(
                        nanoseconds: UInt64(timeoutSec * 1_000_000_000)
                    )
                    guard let self, !Task.isCancelled, !self.closed else { return }
                    let err = AgentError(
                        code: "HUMAN_INPUT_TIMEOUT",
                        message: "No response received within \(timeoutSec)s for human_input_request.",
                        details: ["prompt": captured.prompt, "timeout": timeoutSec],
                        threadId: captured.threadId,
                        refId: "",
                        agentId: captured.agentId,
                        replyTo: self.latestHumanInputRef ?? ""
                    )
                    self.closed = true
                    self.settle(.failure(err))
                    self.thread.closeRun(self)
                }
            }
            thread.fireRequestFeedback(content, self)

        case .output(let content):
            clearHumanInputTimer()
            closed = true
            settle(.success(content))
            thread.closeRun(self)

        case .error(let content):
            clearHumanInputTimer()
            closed = true
            settle(.failure(content))
            thread.closeRun(self)

        case .wait, .plannerCorrection, .unknown:
            // Non-terminal — surfaced to listeners but does not settle.
            break
        }
    }

    /// Sends a reply to the most recent `HumanInputRequest`.
    ///
    /// Throws `RunLifecycleError.closed` when no input is currently
    /// pending. The reply is sent as `user_reply` with `reply_id` set to
    /// the originating request's `ref_id` so the server can route it back
    /// into the paused run.
    public func sendFeedback(_ value: Any) async throws {
        guard let replyId = latestHumanInputRef else {
            throw RunLifecycleError.closed(
                "Run.sendFeedback: no pending human_input_request to respond to."
            )
        }
        // Consume the pending input *before* sending so a reentrant
        // handler doesn't double-respond.
        latestHumanInputRef = nil
        clearHumanInputTimer()
        _ = try await thread.sendReply(value, replyId)
    }

    /// Force-closes the run. Invoked by `AgentThread` on supersede.
    func close(_ reason: String = "Run closed before terminal event") {
        if closed { return }
        clearHumanInputTimer()
        closed = true
        settle(.failure(RunLifecycleError.superseded(reason)))
    }

    private func settle(_ result: Result<AgentOutput, Error>) {
        guard settledResult == nil else { return }
        settledResult = result
        if let cont = continuation {
            continuation = nil
            cont.resume(with: result)
        }
    }

    private func clearHumanInputTimer() {
        humanInputTimer?.cancel()
        humanInputTimer = nil
    }
}
